### ISSUE TITLE
Swagger and Azure

### ISSUE THREAD

**Issue by alexanderschoenberger** [htl-perg-2019-20-5ahif/contact-list-exercise-alexanderschoenberger#1]
[Link to Azure](https://contactlist20191001043807.azurewebsites.net/contacts)
Also implemented the swagger specification.

**Comment by rstropek** [comment]
Nice, you are so far the only one sending me a link to the API reachable via internet 👍. That is worth two extra points. Just one thing: Please format code before checking it in.

Greetings,
Rainer Stropek.
